[package]
name = "robot_localization"
version = "3.5.4"
edition = "2021"

[dependencies]
rosidl_runtime_rs = "0.6"
serde = { version = "1", optional = true, features = ["derive"] }
serde-big-array = { version = "0.5.1", optional = true }

# ROS Dependencies
builtin_interfaces = "*"
diagnostic_msgs = "*"
geographic_msgs = "*"
geometry_msgs = "*"
std_msgs = "*"
unique_identifier_msgs = "*"

[features]
serde = ['dep:serde', 'dep:serde-big-array', 'rosidl_runtime_rs/serde', 'builtin_interfaces/serde', 'diagnostic_msgs/serde', 'geographic_msgs/serde', 'geometry_msgs/serde', 'std_msgs/serde', 'unique_identifier_msgs/serde']

[package.metadata.ros-env]
include = true
